# $Id$
# Authority: shuff
# Upstream: Magnus Erixzon <magnus$erixzon,com>
# ExcludeDist: el2 el3 el4 el5
# Rationale: conflicts with perl-Moose < 1.15

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name WWW-Google-Contacts

Summary: Google Contacts Data API
Name: perl-WWW-Google-Contacts
Version: 0.32
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/WWW-Google-Contacts/

Source: http://search.cpan.org/CPAN/authors/id/M/ME/MERIXZON/WWW-Google-Contacts-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

BuildArch: noarch
BuildRequires: perl
BuildRequires: perl(Class::MOP) >= 1.09
BuildRequires: perl(Crypt::SSLeay)
BuildRequires: perl(ExtUtils::MakeMaker)
BuildRequires: perl(File::Slurp)
BuildRequires: perl(LWP::UserAgent)
BuildRequires: perl(Moose)
BuildRequires: perl(MooseX::Role::Parameterized)
BuildRequires: perl(MooseX::Singleton) >= 0.25
BuildRequires: perl(MooseX::Types)
BuildRequires: perl(Net::Google::AuthSub)
BuildRequires: perl(Perl6::Junction)
BuildRequires: perl(XML::Simple)
BuildRequires: rpm-macros-rpmforge
Requires: perl(Class::MOP) >= 1.09
Requires: perl(Crypt::SSLeay)
Requires: perl(File::Slurp)
Requires: perl(LWP::UserAgent)
Requires: perl(Moose)
Requires: perl(MooseX::Role::Parameterized)
Requires: perl(MooseX::Singleton) >= 0.25
Requires: perl(MooseX::Types)
Requires: perl(Net::Google::AuthSub)
Requires: perl(Perl6::Junction)
Requires: perl(XML::Simple)

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

%description
This module implements 'Google Contacts Data API' according to
http://code.google.com/apis/contacts/docs/3.0/developers_guide_protocol.html

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Makefile.PL INSTALLDIRS="vendor" PREFIX="%{buildroot}%{_prefix}"
%{__make} %{?_smp_mflags}

%install
%{__rm} -rf %{buildroot}
%{__make} pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc Changes META.yml README
%doc %{_mandir}/man?/*
%{perl_vendorlib}/WWW/Google/Contacts.pm
%{perl_vendorlib}/WWW/Google/Contacts/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/*/*/.packlist

%changelog
* Tue Aug 23 2011 Steve Huff <shuff@vecna.org> - 0.32-1
- Initial package.
