# $Id$
# Authority: shuff
# Upstream: Leon Timmermans <leont$cpan,org>

%define perl_vendorlib %(eval "`perl -V:installvendorlib`"; echo $installvendorlib)
%define perl_vendorarch %(eval "`perl -V:installvendorarch`"; echo $installvendorarch)

%define real_name Module-Build-Tiny

Summary: A tiny replacement for Module::Build
Name: perl-Module-Build-Tiny
Version: 0.010
Release: 1%{?dist}
License: Artistic/GPL
Group: Applications/CPAN
URL: http://search.cpan.org/dist/Module-Build-Tiny/

Source: http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/Module-Build-Tiny-%{version}.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root

BuildArch: noarch
BuildRequires: perl >= 5.8.0
BuildRequires: perl(CPAN::Meta)
BuildRequires: perl(Exporter) >= 5.57
BuildRequires: perl(ExtUtils::BuildRC) >= 0.003
BuildRequires: perl(ExtUtils::Helpers) >= 0.007
BuildRequires: perl(ExtUtils::Install)
BuildRequires: perl(ExtUtils::InstallPaths) >= 0.002
BuildRequires: perl(File::Find::Rule)
BuildRequires: perl(File::Slurp)
BuildRequires: perl(File::Spec::Functions)
BuildRequires: perl(Getopt::Long)
BuildRequires: perl(JSON) >= 2
BuildRequires: perl(TAP::Harness)
BuildRequires: rpm-macros-rpmforge

### remove autoreq Perl dependencies
%filter_from_requires /^perl.*/d
%filter_setup

%description
Many Perl distributions use a Build.PL file instead of a Makefile.PL file to
drive distribution configuration, build, test and installation. Traditionally,
Build.PL uses Module::Build as the underlying build system. This module
provides a simple, lightweight, drop-in replacement.

Whereas Module::Build has over 6,700 lines of code; this module has less than
70, yet supports the features needed by most pure-Perl distributions.

%prep
%setup -n %{real_name}-%{version}

# fix problem with modules generated by older versions of Dist::Zilla
#%{?el5:%{__perl} -pi -e '/.*ExtUtils::MakeMaker.*6\.31.*/ && s/6\.3\d/6.30/' Makefile.PL}

%build
%{__perl} Build.PL --installdirs="vendor" --destdir="%{buildroot}"
./Build

%install
%{__rm} -rf %{buildroot}
./Build pure_install
#%{__rm} -rf %{buildroot}%{perl_archlib} %{buildroot}%{perl_vendorarch}

# fix for stupid strip issue
#%{__chmod} -R u+w %{buildroot}/*

%clean
%{__rm} -rf %{buildroot}

%files
%defattr(-, root, root, 0755)
%doc Changes LICENSE META.yml META.json README SIGNATURE Todo
%doc %{_mandir}/man?/*
%{perl_vendorlib}/Module/Build/Tiny.pm
#%{perl_vendorlib}/Module/Build/Tiny/*
#%exclude %{perl_archlib}/perllocal.pod
%exclude %{perl_vendorarch}/auto/*/*/*/.packlist

%changelog
* Mon Aug 29 2011 Steve Huff <shuff@vecna.org> - 0.010-1
- Initial package.
